/* Generated By:JavaCC: Do not edit this line. ConstructorAST1Constants.java */
package descendente;

public interface ConstructorAST1Constants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExponencial = 6;
  int pint = 9;
  int real = 10;
  int bool = 11;
  int ptrue = 12;
  int pfalse = 13;
  int string = 14;
  int and = 15;
  int or = 16;
  int not = 17;
  int pnull = 18;
  int proc = 19;
  int pif = 20;
  int then = 21;
  int pelse = 22;
  int endif = 23;
  int pwhile = 24;
  int pdo = 25;
  int endwhile = 26;
  int call = 27;
  int record = 28;
  int array = 29;
  int of = 30;
  int pointer = 31;
  int pnew = 32;
  int delete = 33;
  int read = 34;
  int write = 35;
  int nl = 36;
  int var = 37;
  int type = 38;
  int Separacion = 39;
  int PtoComa = 40;
  int asig = 41;
  int equiv = 42;
  int mas = 43;
  int menos = 44;
  int id = 45;
  int Nentero = 46;
  int Nreal = 47;
  int literalCad = 48;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"true\"",
    "\"false\"",
    "\"string\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "\"&&\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "<id>",
    "<Nentero>",
    "<Nreal>",
    "<literalCad>",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"->\"",
    "\"*\"",
    "\">\"",
    "\"<\"",
    "\"/\"",
    "\"%\"",
  };

}
