
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AAscendente_Tiny1.analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SEP = 23;
  public static final int DISTINTO = 18;
  public static final int PCIERRE = 6;
  public static final int INT = 25;
  public static final int ARRAY = 50;
  public static final int WRITE = 56;
  public static final int DELETE = 54;
  public static final int LLAVECERRADA = 33;
  public static final int NOT = 12;
  public static final int MENORIGUAL = 14;
  public static final int AND = 10;
  public static final int IGUAL = 7;
  public static final int NREAL = 4;
  public static final int RECORD = 49;
  public static final int TYPE = 59;
  public static final int OR = 11;
  public static final int BOOL = 27;
  public static final int CALL = 48;
  public static final int DIV = 22;
  public static final int CORCERRADO = 31;
  public static final int IF = 41;
  public static final int ENDWHILE = 47;
  public static final int ID = 2;
  public static final int OF = 51;
  public static final int PTOCOMA = 24;
  public static final int MAYORIGUAL = 16;
  public static final int EOF = 0;
  public static final int AMP = 37;
  public static final int TRUE = 8;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int MUL = 21;
  public static final int MODULO = 29;
  public static final int MENOS = 20;
  public static final int NULL = 39;
  public static final int MENOR = 13;
  public static final int LLAVEABIERTA = 32;
  public static final int REAL = 26;
  public static final int MAYOR = 15;
  public static final int LITERALCAD = 28;
  public static final int PAP = 5;
  public static final int FLECHA = 35;
  public static final int NENT = 3;
  public static final int ENDIF = 44;
  public static final int ELSE = 43;
  public static final int PUNTO = 34;
  public static final int NL = 57;
  public static final int READ = 55;
  public static final int WHILE = 45;
  public static final int THEN = 42;
  public static final int CORABIERTO = 30;
  public static final int PROC = 40;
  public static final int STRING = 38;
  public static final int COMPARACION = 17;
  public static final int POINTER = 52;
  public static final int FALSE = 9;
  public static final int VAR = 58;
  public static final int DO = 46;
  public static final int MAS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "NENT",
  "NREAL",
  "PAP",
  "PCIERRE",
  "IGUAL",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "COMPARACION",
  "DISTINTO",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "SEP",
  "PTOCOMA",
  "INT",
  "REAL",
  "BOOL",
  "LITERALCAD",
  "MODULO",
  "CORABIERTO",
  "CORCERRADO",
  "LLAVEABIERTA",
  "LLAVECERRADA",
  "PUNTO",
  "FLECHA",
  "COMA",
  "AMP",
  "STRING",
  "NULL",
  "PROC",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "CALL",
  "RECORD",
  "ARRAY",
  "OF",
  "POINTER",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "VAR",
  "TYPE"
  };
}

