/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTiny1Constants.java */
package ASintTiny1;

public interface AnalizadorSintacticoTiny1Constants {

  int EOF = 0;
  int letra = 3;
  int digitoPositivo = 4;
  int digito = 5;
  int parteEntera = 6;
  int parteDecimal = 7;
  int parteExp = 8;
  int literalCad = 9;
  int id = 10;
  int numeroEntero = 11;
  int numeroReal = 12;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExp>",
    "<literalCad>",
    "<id>",
    "<numeroEntero>",
    "<numeroReal>",
    "\"&&\"",
    "\";\"",
    "\"var\"",
    "\"proc\"",
    "\"int\"",
    "\"bool\"",
    "\"real\"",
    "\"string\"",
    "\"array\"",
    "\"[\"",
    "\"]\"",
    "\"of\"",
    "\"record\"",
    "\"{\"",
    "\"}\"",
    "\"pointer\"",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\"=\"",
    "\"if\"",
    "\"then\"",
    "\"endif\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"new\"",
    "\"delete\"",
    "\"call\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"not\"",
    "\"*\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"and\"",
    "\"or\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
    "\".\"",
    "\"->\"",
  };

}
