
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ascendente.analizadorSintactico;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int SEP = 20;
  public static final int DISTINTO = 15;
  public static final int PCIERRE = 3;
  public static final int INT = 22;
  public static final int ARRAY = 46;
  public static final int WRITE = 52;
  public static final int DELETE = 50;
  public static final int LLAVECERRADA = 29;
  public static final int NOT = 9;
  public static final int MENORIGUAL = 11;
  public static final int AND = 7;
  public static final int NREAL = 59;
  public static final int IGUAL = 4;
  public static final int RECORD = 45;
  public static final int TYPE = 55;
  public static final int OR = 8;
  public static final int BOOL = 24;
  public static final int CALL = 44;
  public static final int DIV = 19;
  public static final int CORCERRADO = 27;
  public static final int IF = 37;
  public static final int ID = 56;
  public static final int ENDWHILE = 43;
  public static final int OF = 47;
  public static final int PTOCOMA = 21;
  public static final int MAYORIGUAL = 13;
  public static final int EOF = 0;
  public static final int AMP = 33;
  public static final int TRUE = 5;
  public static final int NEW = 49;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int COMA = 32;
  public static final int MODULO = 25;
  public static final int MENOS = 17;
  public static final int NULL = 35;
  public static final int MENOR = 10;
  public static final int LLAVEABIERTA = 28;
  public static final int REAL = 23;
  public static final int MAYOR = 12;
  public static final int LITERALCAD = 57;
  public static final int PAP = 2;
  public static final int NENT = 58;
  public static final int FLECHA = 31;
  public static final int ENDIF = 40;
  public static final int ELSE = 39;
  public static final int PUNTO = 30;
  public static final int NL = 53;
  public static final int READ = 51;
  public static final int WHILE = 41;
  public static final int THEN = 38;
  public static final int CORABIERTO = 26;
  public static final int PROC = 36;
  public static final int COMPARACION = 14;
  public static final int STRING = 34;
  public static final int POINTER = 48;
  public static final int FALSE = 6;
  public static final int VAR = 54;
  public static final int DO = 42;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAP",
  "PCIERRE",
  "IGUAL",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "COMPARACION",
  "DISTINTO",
  "MAS",
  "MENOS",
  "MUL",
  "DIV",
  "SEP",
  "PTOCOMA",
  "INT",
  "REAL",
  "BOOL",
  "MODULO",
  "CORABIERTO",
  "CORCERRADO",
  "LLAVEABIERTA",
  "LLAVECERRADA",
  "PUNTO",
  "FLECHA",
  "COMA",
  "AMP",
  "STRING",
  "NULL",
  "PROC",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "WHILE",
  "DO",
  "ENDWHILE",
  "CALL",
  "RECORD",
  "ARRAY",
  "OF",
  "POINTER",
  "NEW",
  "DELETE",
  "READ",
  "WRITE",
  "NL",
  "VAR",
  "TYPE",
  "ID",
  "LITERALCAD",
  "NENT",
  "NREAL"
  };
}

