package AnalizadorLexico_Manual;

public enum ClaseLexica {
 ID, NENT, NREAL, PAP, PCIERRE, IGUAL, TRUE, FALSE,
 AND, OR, NOT, MENOR, MENORIGUAL, MAYOR, MAYORIGUAL, COMPARACION,
 DISTINTO, MAS, MENOS, MUL, DIV, SEP, PTOCOMA, INT, REAL, BOOL, EOF,
 EXPRES, DEC

}
